export enum IconName {
  Ado = 'ado',
  Apple = 'apple',
  ArrowDown = 'arrow-down',
  ArrowUp = 'arrow-up',
  Bitmart = 'bitmart',
  Changelly = 'changelly',
  closeNav = 'close-nav',
  Dextools = 'dextools',
  Discord = 'discord',
  Docker = 'docker',
  EmptyState = 'empty-state',
  Gate = 'gate',
  Github = 'github',
  Hamburguer = 'hamburguer',
  Letsexchange = 'letsexchange',
  Linux = 'linux',
  Mexc = 'mexc',
  MyWitWallet = 'my-wit-wallet',
  NavitagionCursor = 'navitagion-cursor',
  Oneinch = 'oneinch',
  Pancakeswap = 'pancakeswap',
  Raspberry = 'raspberry',
  RightArrow = 'right-arrow',
  Sheikah = 'sheikah',
  Simpleswap = 'simpleswap',
  Telegram = 'telegram',
  Uniswap = 'uniswap',
  Windows = 'windows',
  X = 'x'
}

export const iconNames = Object.values(IconName)
